[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.29.0"
ci                 = "github"
installers         = ["shell", "npm", "homebrew"]
targets            = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
install-path       = "CARGO_HOME"
install-updater    = true
tap                = "paholg/homebrew-tap"
publish-jobs       = ["homebrew", "npm"]
