on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Check

jobs:
  all-succeeded:
    name: All Succeeded
    if: always()
    runs-on: ubuntu-latest
    needs:
    - test
    - lint

    steps:
      - name: Check if all jubs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v2
      - uses: moonrepo/setup-rust@v1
        with:
          inerhit-toolchain: true
          bins: cargo-nextest
      - uses: fish-actions/install-fish@v1
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: Configure ZSH
        run: echo "compinit -u" > ~/.zshrc
      - name: Configure Bash
        run: |
          cat > ~/.bashrc << 'EOF'
          # Force interactive mode detection
          [[ $- != *i* ]] && exec bash -i "$0" "$@"

          # Set interactive options
          set -i
          set -m  # Enable job control

          # Basic interactive settings
          export PS1='$ '
          export TERM=xterm-256color
          EOF
      - run: just test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v2
      - uses: moonrepo/setup-rust@v1
        with:
          inerhit-toolchain: true
          components: clippy, rustfmt
      - run: just lint
