on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Check

jobs:
  all-succeeded:
    name: All Succeeded
    if: always()
    runs-on: ubuntu-latest
    needs:
    - check

    steps:
      - name: Check if all jubs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nixbuild/nix-quick-install-action@v32
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          paths: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
      - run: nix build
      - run: nix flake check --print-build-logs
